import { createFileRoute } from "@tanstack/react-router";
import { PublicShell } from "@/components/layout/PublicShell";

export const Route = createFileRoute("/terms")({
  head: () => ({ meta: [{ title: "Terms of service — Call Me AI" }] }),
  component: TermsPage,
});

function TermsPage() {
  return (
    <PublicShell>
      <section className="mx-auto max-w-2xl px-4 py-20 sm:px-6 md:py-28">
        <p className="text-[10px] font-semibold uppercase tracking-[0.2em] text-primary">
          Legal
        </p>
        <h1 className="mt-3 font-serif text-4xl tracking-tight text-foreground md:text-5xl">
          Terms of service
        </h1>
        <p className="mt-2 text-xs text-muted-foreground">Last updated: today</p>

        <div className="prose prose-invert mt-8 max-w-none space-y-5 text-sm text-foreground/80">
          <p>
            By using Call Me AI you agree to the following. The plain-English
            version is on the left; the legal version is the binding one.
          </p>
          <h2 className="font-serif text-xl text-foreground">1. Eligibility</h2>
          <p>
            You must be 18 or older to use Call Me AI. By using the service
            you confirm that you are.
          </p>
          <h2 className="font-serif text-xl text-foreground">2. The service</h2>
          <p>
            Call Me AI is a conversational AI product. Conversations are
            generated by machine-learning models. Outputs may be inaccurate,
            and personas are fictional characters. Do not rely on outputs for
            medical, legal, or financial decisions.
          </p>
          <h2 className="font-serif text-xl text-foreground">3. Acceptable use</h2>
          <p>
            You agree not to use the service to generate illegal content,
            content involving minors, content depicting real people without
            consent, or content that infringes on someone else's rights. Full
            acceptable-use policy at <a href="/acceptable-use" className="underline">/acceptable-use</a>.
          </p>
          <h2 className="font-serif text-xl text-foreground">4. Account and billing</h2>
          <p>
            You are responsible for your account. Paid plans are billed by
            our merchant-of-record partner. You can cancel any time; you keep
            access until the end of the current billing period.
          </p>
          <h2 className="font-serif text-xl text-foreground">5. Termination</h2>
          <p>
            We may suspend or terminate accounts that violate these terms or
            our safety policy.
          </p>
          <h2 className="font-serif text-xl text-foreground">6. Changes</h2>
          <p>
            We may update these terms. Material changes will be announced on
            this page.
          </p>
          <h2 className="font-serif text-xl text-foreground">7. Contact</h2>
          <p>
            Questions:{" "}
            <a href="mailto:hello@callmeai.io" className="underline">
              hello@callmeai.io
            </a>
          </p>
        </div>
      </section>
    </PublicShell>
  );
}
